import Header from '@/components/layout/(header)/Header.jsx'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/layout/(footer)/Footer'
import { Providers } from "./providers";
import { ThemeSwitcher } from '@/components/layout/(header)/ThemeSwitcher'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={inter.className}>
        <Providers>

          <Header />
          {children}
          <ThemeSwitcher />
          {/* <Footer /> */}

        </Providers>
      </body>
    </html>
  )
}