import Header from '@/components/layout/(header)/Header.jsx'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/layout/(footer)/Footer'
import AuthProvider from './context/AuthProvider'
import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <Header />
            {children}
            {/* <Footer /> */}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  )
}