export interface SignupType{
  loginId : string, 
  password : string,
  name : string,
  birthdate : string,
  gender : string,
  phoneNumber : string,
  nickname : string,
  emailNotificationStatus: boolean,
  smsNotificationStatus: boolean,
  pushNotificationStatus: boolean,
  checkPassword: string,
  companyEmail: string,
  companyId: string,
  companyName: string,
  certificateImageUrl: string,
}